### ISSUE TITLE
Nonfunctional on iPhone

### ISSUE THREAD

**Issue by xp2-882030kgz010602** [octoman90/Genshin-Party-Builder#130]
I don't know if it's my phone or not, but I just get a black screen on iPhone. I'm using the iPhone 7+ on iOS 12.4. That's all I know.

**Comment by octoman90** [comment]
Thank you for the report! Which browser do you use: Safari (with a compass icon) or Chrome (with a multicoloured disc icon)?

**Comment by xp2-882030kgz010602** [comment]
Thanks! Seems functional now.
