### ISSUE TITLE
Adjustments to the suggestions

### ISSUE THREAD

**Issue by HyperEnte** [octoman90/Genshin-Party-Builder#164]
I would like to point out a few things that could be improved:
- Tartaglia, Ganyu and Noelle are not affected by Bennets C6
- Rosaria can actually benefit from C6 Bennet in reverse melt teams
- Ayaka should be added to the Bennet list because his C6 overwrites her normal attacks which can mess up the freeze setup

- Tartaglia, Hu Tao, Klee, Noelle and Yoimiya are not affected by Chongyun

- When Hu Tao is in the team healers should get recommended less
- When Pyro in general is the main dps a hydro character should get recommended more
- When Cryo is the main dps hydro characters (especially Kokomi, Mona and Xingqiu) should get recommended more
- When Electro is in the team dendro should get recommended more and vice versa

**Comment by octoman90** [comment]
Thank you, these are some nice catches!
There's already a system that gives characters points based on possible elemental reactions according to the matrix below. I am still unsure about the exact coefficients, though, especially for dendro. Also, it doesn't distinguish between main DPS and other characters and I'm not sure if that's needed.

|         | anemo | cryo | dendro | electro | geo | hydro | pyro |
|---------|-------|------|--------|---------|-----|-------|------|
| anemo   | 0     | 1    | 0      | 1       | 0   | 1     | 1    |
| cryo    | 1     | 0    | 0      | 1       | 0.5 | 1     | 1.5  |
| dendro  | 0     | 0    | 0      | 1.3     | 0   | 1.3   | 0.9  |
| electro | 1     | 1    | 1.3    | 0       | 0.5 | 1     | 1    |
| geo     | 0     | 0.5  | 0      | 0.5     | 0   | 0.5   | 0.5  |
| hydro   | 1     | 1    | 1.3    | 1       | 0.5 | 0     | 1.5  |
| pyro    | 1     | 1.5  | 0.9    | 1       | 0.5 | 1.5   | 0    |

**Comment by octoman90** [comment]
> Maybe make dendro-electro and cryo-hydro a bit higher since those are very important reactions for most characters with those elements

Good call.
