### ISSUE TITLE
[suggestion] character sorting

### ISSUE THREAD

**Issue by isaswa** [octoman90/Genshin-Party-Builder#166]
I think it'll be better for users to select if they want to sort characters by element or star rank, rather than the current alphabet sorting.

**Comment by octoman90** [comment]
Thanks, that's a great idea! I'll look into implementing it soon.

**Comment by octoman90** [comment]
The option for sorting characters in both the main character selection screen and character selection pop-up has been added in commits 3e85db4390b163cadc275cf47352a4f23c94aea0 and 64dc67c7e3efe04579daf8c02a110c949ae185ad. You can now switch between sorting by name, rarity and element!
