### ISSUE TITLE
Website does not accept GOOD version 2

### ISSUE THREAD

**Issue by Cupcak3** [octoman90/Genshin-Party-Builder#172]
Inventory Kamera will begin marking it's export data as GOOD version 2 in v1.3.5 (unreleased yet). The website says this format is unsupported and editing the version field from 2 to 1 imports fine. GOOD version 2 is backwards compatible with version 1. Version 1 support is hardcoded at [src/utils/readGOOD.ts](https://github.com/octoman90/Genshin-Party-Builder/blob/20941e88fc8bece5db7854a579b1c416158a327b/src/utils/readGOOD.ts) .
![image](https://user-images.githubusercontent.com/8845977/208266481-caafb1c1-78ba-458f-9d08-e8169ae24fd0.png)

**Comment by octoman90** [comment]
I allowed import from GOODv2, thank you for the heads-up!
