### ISSUE TITLE
Sara and Shogun not available on the website

### ISSUE THREAD

**Issue by LostLogic** [octoman90/Genshin-Party-Builder#60]
Hello!
Noticed Sara and Shogun has been updated on Git, but not on the site.
Will they be added on the site soon?

**Comment by octoman90** [comment]
They are available now, thank you for reminding me to upload a fresh version.
I really should come up with a way to automate this...

**Comment by LostLogic** [comment]
That would be ideal yeah! Checked and Sara and Shogun are up and available. I guess Alloy will be added later on with the next character.
Thanks for the quick fix and the site!
Wish you an excellent weekend and many ⭐⭐⭐⭐⭐ characters in your future 😁
